[project]
authors = ["Cristian Garcia <cgarcia.e88@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
name = "aoc-2024"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
modular = ">=25.4.0.dev2025060805,<26"
ipykernel = ">=6.29.5,<7"
max = ">=25.4.0.dev2025060513,<26"
